[package]
name = "hmm-rust"
version = "0.1.0"
authors = ["Vilém Zouhar <vilem.zouhar@gmail.com>"]
edition = "2018"

[dependencies]
rand = "^0.7"

[features]
default = []
fast = ["skip_cum"]
skip_cum = []
print_trellis = []
print_pred_sent = []
print_acc = []
print_pred = []